### ISSUE TITLE
Data Privacy & Security

### ISSUE THREAD

**Issue by martab0** [KinRap/GenerativeAIForTechWriters#9]
Rozdział wymaga przeredagowania w zakresie przekraczającym moje review. Są w nim informacje prawdziwe, ale pomieszane:
- prawa własności do danych i treści, na których trenuje się AI;
- ochrona danych (w tym danych osobowych) osób i firm, które zadają pytania do AI.

Kwestia własności intelektualnej treści otrzymanych z AI należy już do rozdziału "Legal & Ethical Issues".

**Comment by KinRap** [comment]
Wyrzuciłam stąd fragmenty dotyczące własności intelektualnej. Dopisałam informacje na temat sposobu pozyskiwania danych przez GenAI, co w dużym stopniu wyjaśnia kwestie ryzyka ujawniania danych. Wydaje mi się, że teraz jest to wszystko bardziej spójne i klarowne, ale jeśli mozesz to zerknij jeszcze proszę na to.
